env:
  es6: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
globals:
  angular: true
  describe: true
  beforeEach: true
  inject: true
  spyOn: true
  it: true
  expect: true
  window: true
rules:
  indent:
    - 2
    - 2
  linebreak-style:
    - 2
    - unix
  quotes:
    - 2
    - single
  semi:
    - 2
    - always
  no-return-assign:
    - 2
    - always
