---
-
  hosts: all
  gather_facts: false
  remote_user: vagrant
  become: yes
  become_method: sudo

  tasks:
    -
      name: apt-get update
      apt:
        update_cache: yes

    -
      name: install git
      apt:
        name: git
        state: latest
        update_cache: yes

