---
-
  hosts: all

  tasks:
    - name: apt-get update
      apt:
        update_cache: yes
      remote_user: vagrant
      become: yes
      become_method: sudo

    - name: install git
      apt:
        name: git
        state: latest
        update_cache: yes
      remote_user: vagrant
      become: yes
      become_method: sudo

    - include: tasks/nvm.yml

    - include: tasks/node.yml
      vars:
        node_version: 6.9.1
