- name: install packages for nvm
  apt: name={{ item }}
  with_items:
    - curl
    - build-essential
    - libssl-dev
  tags: nvm

- name: download nvm
  git: repo=https://github.com/creationix/nvm.git dest=~/.nvm version=v0.32.1
  tags: nvm

- name: source nvm in ~/.profile
  become: yes
  become_user: vagrant
  lineinfile: dest=~/.profile line="source ~/.nvm/nvm.sh"
  tags: nvm
